name: Darren Powell
favicon: null
layout_spectrum: 0.5360581986606121
typography_spectrum: 0.22779429447837174
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.07863155077211559
  lightness: 0.735257190419361
  saturation: 0.4844878858420998
  rhythmicContrast: 0.40933718043379486
purpose: []
